### ISSUE TITLE
Bug Alert (SOLVED)

### ISSUE THREAD

**Issue by GabrielBX** [VirtualOx-sys/crunchyroll-Premium#1]
"crunchyroll-Premium" is not available

when you enter the site it is loading for a while and it appears that "the video will start soon" but it never ends

**Comment by VirtualOx-sys** [comment]
Apparently yesterday the Crunchyroll website was updated, changing some established parameters for the extension to work in the beta version.

Work will be done to get everything back to normal in a few hours.

**Comment by GabrielBX** [comment]
Is it difficult to fix the Crunchyroll premium?...
I hope you get it soon...

**Comment by VirtualOx-sys** [comment]
> Is it difficult to fix the Crunchyroll premium?... I hope you get it soon...

I still can't find the new identifier for each episode. That was the problem that triggered the whole error.

**Comment by GabrielBX** [comment]
.... ok, I will wait patiently

**Comment by GabrielBX** [comment]
how i can fixes the crunchyroll plug-in with the new reproductor-crp?

**Comment by VirtualOx-sys** [comment]
> how i can fixes the crunchyroll plug-in with the new reproductor-crp?

The crp-player plugin is the problem. Because there is the engine that makes the extension work, specifically in the path player-crp/assets/js/player.js

Located on line 26.

**Comment by LeinadUchiha** [comment]
I saw that you have an engine that allows the correct operation of the Crunchyroll Premium extension (player-crp), I wanted to know if this can already be implemented for operation or it is not yet possible?
