### ISSUE TITLE
Cargando infinitamente

### ISSUE THREAD

**Issue by SamuelFriHer** [VirtualOx-sys/Crunchyroll-Premium#3]
Se queda así eternamente, me pasa con todas las extensiones que he probado.

![Captura de pantalla de 2023-02-07 23-39-18](https://user-images.githubusercontent.com/117464705/217392230-4f8991e4-04d4-4c3e-8202-6811d929e655.png)

**Comment by VirtualOx-sys** [comment]
> Se queda así eternamente, me pasa con todas las extensiones que he probado.
> 
> ![Captura de pantalla de 2023-02-07 23-39-18](https://user-images.githubusercontent.com/117464705/217392230-4f8991e4-04d4-4c3e-8202-6811d929e655.png)

Si, ya tengo en conocimiento dicho error; Sin embargo, como la extensión trabaja actualmente extrayendo datos de diferentes API's y no directamente desde Crunchyroll, la empresa aplica constantes actualizaciones a sus sistemas para evitar esto. 

Actualmente se esta trabajando en una nueva alternativa para evadir las restricciones y poner en funcionamiento la extensión nuevamente.

**Comment by VirtualOx-sys** [comment]
**Resuelto**

**Comment by VirtualOx-sys** [comment]
✔ **Resuelto**
