### ISSUE TITLE
como puedo ver los capítulos doblados?

### ISSUE THREAD

**Issue by genaro123dpp** [VirtualOx-sys/Crunchyroll-Premium#4]
como puedo ver los capítulos doblados?

**Comment by VirtualOx-sys** [comment]
> como puedo ver los capítulos doblados?

Cambiando el idioma de los episodios directamente desde las configuraciones. Aunque desconozco si está funcionando actualmente.

**Comment by genaro123dpp** [comment]
me sale solo la calidad, subtítulos y velocidad

**Comment by VirtualOx-sys** [comment]
> me sale solo la calidad, subtítulos y velocidad

Desde las configuraciones de cuenta de crunchyroll. No del reproductor.

**Comment by genaro123dpp** [comment]
nop. esta en español (america latina) los subtitulos y el audio. pero no se dobla

**Comment by VirtualOx-sys** [comment]
> nop. esta en español (america latina) los subtitulos y el audio. pero no se dobla

Se revisarán las causas y se tratara de solucionar el problema.

**Comment by VirtualOx-sys** [comment]
> a mi nunca termina de cargarme se que da cargando infinitamente 
> ![image](https://github.com/VirtualOx-sys/Crunchyroll-Premium/assets/82487805/f585137b-e312-46b7-b3a8-6e6253b78a76)
> 

Eso pasaba en la versión 1.4.3

Actualmente la extensión está en la versión 1.5 funcionando correctamente. Actualicé la extensión descargando el último lanzamiento y todos los problemas que vienen desde a tes serán solucionado.

**Comment by VirtualOx-sys** [comment]
> ![image](https://github.com/VirtualOx-sys/Crunchyroll-Premium/assets/82487805/e1bd2008-80b0-4001-bfe5-5c288bd9de7e)
> tengo el 1.5.3 y me sigue saliendo ese error

Es raro porque a partir de la versión 1.5 se solucionó dicho bucle.

**Comment by VirtualOx-sys** [comment]
> > > ![image](https://user-images.githubusercontent.com/82487805/284084116-e1bd2008-80b0-4001-bfe5-5c288bd9de7e.png)
> > > tengo el 1.5.3 y me sigue saliendo ese error
> > 
> > Es raro porque a partir de la versión 1.5 se solucionó dicho bucle.
> 
> ![image](https://github.com/VirtualOx-sys/Crunchyroll-Premium/assets/82487805/61263620-5216-46a9-90a2-481341a8d252)
> me salen esos errores 
> 

Se estarán investigando los posibles problemas que le afectan.

Cierro el hilo.
