### ISSUE TITLE
Los episodios doblados siguen sin funcionar

### ISSUE THREAD

**Issue by belgarrub** [VirtualOx-sys/Crunchyroll-Premium#6]
Entre con mi cuenta y los puse en castellano y no los reproduce en castellano si no en japones con subtítulos

**Comment by VirtualOx-sys** [comment]
> Entre con mi cuenta y los puse en castellano y no los reproduce en castellano si no en japones con subtítulos

Al parecer han cambiado nuevamente la manera en la que se obtienen los episodios doblados. Se trabajará en una solución.
