### ISSUE TITLE
Cannot change the language

### ISSUE THREAD

**Issue by Surcof** [VirtualOx-sys/Crunchyroll-Premium#7]
Hello, even if i log in i can't change the audio of the video, is there any way to force a specific language? i would like to edit the code to insert the 'itIT' lang but i can't undearstand how.
thank you

**Comment by VirtualOx-sys** [comment]
> Hello, even if i log in i can't change the audio of the video, is there any way to force a specific language? i would like to edit the code to insert the 'itIT' lang but i can't undearstand how. thank you

Hello, I had already answered a similar problem.

Apparently they've changed the way episodes are dubbed again. We will work on a version where existing problems are resolved.
